### ISSUE TITLE
use of shared worked for turbo_stream_from

### ISSUE THREAD

**Issue by acetinick** [le0pard/cable-shared-worker#16]
I am looking to find a way that all streams created using [turbo_stream_from](https://rubydoc.info/github/hotwired/turbo-rails/main/Turbo%2FStreamsHelper:turbo_stream_from) in Turbo will also go through the shared worker? is this possible in some way?

**Comment by le0pard** [comment]
for this you need create something, which will integrated with `turbo-cable-stream-source` web component. This library not designed for this

https://github.com/hotwired/turbo-rails/blob/main/app/javascript/turbo/cable_stream_source_element.js
